///////////////////////////////////////////////////////////////////////////////
// TcpClient.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TcpClient.h"
#include "TcpClientVersion.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CTcpClient
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CTcpClient
BEGIN_INTERFACE_MAP(CTcpClient)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
	INTERFACE_ENTRY(IID_ITcIoTcpProtocolRecv, ITcIoTcpProtocolRecv)
///</AutoGeneratedContent>
END_INTERFACE_MAP()


IMPLEMENT_IPERSIST_LIB(CTcpClient, VID_TcpClient, CID_TcpClientCTcpClient)
IMPLEMENT_ITCOMOBJECT(CTcpClient)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CTcpClient)
IMPLEMENT_ITCADI(CTcpClient)
IMPLEMENT_ITCWATCHSOURCE(CTcpClient)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of CTcpClient 
BEGIN_SETOBJPARA_MAP(CTcpClient)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_TcpClientTcpServerIpAddress, m_TcpServerIpAddress)
	SETOBJPARA_VALUE(PID_TcpClientTcpServerPort, m_TcpServerPort)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
	SETOBJPARA_ITFPTR(PID_TcpClientTcpProt, m_spTcpProt)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CTcpClient 
BEGIN_GETOBJPARA_MAP(CTcpClient)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_TcpClientTcpServerIpAddress, m_TcpServerIpAddress)
	GETOBJPARA_VALUE(PID_TcpClientTcpServerPort, m_TcpServerPort)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
	GETOBJPARA_ITFPTR(PID_TcpClientTcpProt, m_spTcpProt)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CTcpClient
BEGIN_OBJPARAWATCH_MAP(CTcpClient)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CTcpClient
BEGIN_OBJDATAAREA_MAP(CTcpClient)
///<AutoGeneratedContent id="ObjectDataAreaMap">
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CTcpClient::CTcpClient()
	: m_Trace(m_TraceLevelMax, m_spSrv)
	, m_TraceLevelMax(tlAlways)
{
	m_SockId = 0;
	m_spTcpProt = NULL;
	m_bSendRequest = true;
	m_connections = 0;
}

///////////////////////////////////////////////////////////////////////////////
CTcpClient::~CTcpClient() 
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CTcpClient)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CTcpClient::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CTcpClient::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	if (SUCCEEDED(hr) && m_spTcpProt.HasOID())
	{
		hr = m_spSrv->TcQuerySmartObjectInterface(m_spTcpProt);
	}

	// If following call is successful the CycleUpdate method will be called, 
	// eventually even before method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller(); 

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller(); 
	}
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CTcpClient::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	RemoveModuleFromCaller();

	if (m_SockId != 0)
	{
		if (m_spTcpProt->IsConnected(m_SockId) == S_OK)
		{
			m_spTcpProt->Close(m_SockId);
			m_spTcpProt->CheckReceived();
		}

		m_spTcpProt->FreeSocket(m_SockId);
		m_SockId = 0;
	}


	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CTcpClient::SetObjStateSP()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CTcpClient::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	m_spTcpProt->CheckReceived();

	if ( m_SockId == 0 )
	{
		if (SUCCEEDED_DBG(hr = m_spTcpProt->AllocSocket(THIS_CAST(ITcIoTcpProtocolRecv), m_SockId)))
		{
			if (FAILED(hr = m_spTcpProt->Connect(m_SockId, ((PULONG)&m_TcpServerIpAddress)[0], m_TcpServerPort)))
			{
				m_spTcpProt->FreeSocket(m_SockId);
				m_SockId = 0;
			}
			else {
				m_connections++; //count number of connections
			}

		}
	}
	else if (m_bSendRequest)
	{
		if (hr = m_spTcpProt->IsConnected(m_SockId) == S_OK)
		{
			if (hr == S_OK) {
				m_Trace.Log(tlInfo, FLEAVEA "Connection successfull: SocketId: %d", m_SockId);
				PCHAR pRequest = "GET / HTTP/1.1\r\nHOST: beckhoff.com\r\n\r\n";
				ULONG nSendData = 0;
				m_spTcpProt->SendData(m_SockId, strlen(pRequest), pRequest, nSendData);
				m_bSendRequest = false;
			}
			else 
			{
				m_Trace.Log(tlVerbose, FLEAVEA "Not (yet) connected: SocketId: %d", m_SockId);
			}
		}
		else
			m_Trace.Log(tlError, FLEAVEA "Fatal Error by IsConnected() on SocketId %d", m_SockId);
		
	}


	return hr;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT CTcpClient::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CTcpClient::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);
	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;
	m_Trace.Log(tlVerbose, FLEAVEA);
}


///<AutoGeneratedContent id="ImplementationOf_ITcIoTcpProtocolRecv">
HRESULT CTcpClient::ReceiveData(ULONG socketId, ULONG nData, PVOID pData)
{
	HRESULT hr = S_OK;

	PCHAR pResponse = new CHAR[100];
	if (pResponse != NULL)
	{		
		memset(pResponse, 0, 100);
		int endpos = min(100, nData);
		memcpy(pResponse, pData, endpos);
		pResponse[endpos] = 0; //\0 term

		m_Trace.Log(tlInfo, FLEAVEA "Receive answer w/ length %d : first 100 chars:'%s'", nData, pResponse);

		delete[] pResponse;
	}
	return hr;
}

HRESULT CTcpClient::ReceiveEvent(ULONG socketId, TCPIP_EVENT tcpEvent)
{
	m_Trace.Log(tlInfo, FLEAVEA "Receive TCP Event: SocketId: %d Event: %d", socketId, tcpEvent);

	switch (tcpEvent)
	{
	case TCPIP_EVENT_RESET:
	case TCPIP_EVENT_TIMEOUT:
		if (socketId == m_SockId)
		{
			m_Trace.Log(tlInfo, FLEAVEA "Connection to remote server failed!");
		}
		m_SockId = 0; 
		break;
	case TCPIP_EVENT_CONN_CLOSED:
		m_Trace.Log(tlInfo, FLEAVEA "Close connection: SocketId: %d", socketId);
		m_spTcpProt->FreeSocket(socketId);
		m_SockId = 0;
		break;
	case TCPIP_EVENT_CONN_INCOMING:
		break;
	case TCPIP_EVENT_KEEP_ALIVE:
		break;
	case TCPIP_EVENT_CONN_IDLE:
		break;
	case TCPIP_EVENT_DATA_SENT:
	case TCPIP_EVENT_DATA_RECEIVED:
		break;
	case TCPIP_EVENT_LINKCONNECT:
		break;
	case TCPIP_EVENT_LINKDISCONNECT:
		m_Trace.Log(tlInfo, FLEAVEA "link disconnect connection: SocketId: %d", socketId);
		m_spTcpProt->FreeSocket(socketId);
		m_SockId = 0;
		break;
	case TCPIP_EVENT_ERROR:
	default:
		break;
	}

	return S_OK;
}
///</AutoGeneratedContent>
