///////////////////////////////////////////////////////////////////////////////
// UdpDemoServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_UdpDemo = 0x3F000000;
#define SRVNAME_UDPDEMO "UdpDemo"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_UdpDemoCUdpDemo = {0xf47d354c,0x1bc6,0x4e2a,{0x84,0xc7,0x81,0xef,0xa1,0xd6,0x20,0x25}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_UdpDemoUdpProt = 0x00000001;
const PTCID PID_UdpDemoUdpProt2 = 0x00000002;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_644F3385_C5F8_4BFB_B16A_FB99EAC8BB62_INCLUDED_)
#define _TC_TYPE_644F3385_C5F8_4BFB_B16A_FB99EAC8BB62_INCLUDED_
typedef struct _ETYPE_VLAN_HEADER
{
	USHORT VLanType;
	unsigned char VLanIdH : 4;
	unsigned char reserved1 : 1;
	unsigned char Priority : 3;
	unsigned char VLanIdL : 8;
} ETYPE_VLAN_HEADER, *PETYPE_VLAN_HEADER;
#endif // !defined(_TC_TYPE_644F3385_C5F8_4BFB_B16A_FB99EAC8BB62_INCLUDED_)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_03010097_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_IID_03010097_0000_0000_E000_000000000064_INCLUDED_
TCOM_DECL_INTERFACE("03010097-0000-0000-e000-000000000064", ITcIoUdpProtocol)
#endif // !defined(_TC_IID_03010097_0000_0000_E000_000000000064_INCLUDED_)

#if !defined(_TC_IID_03010095_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_IID_03010095_0000_0000_E000_000000000064_INCLUDED_
TCOM_DECL_INTERFACE("03010095-0000-0000-e000-000000000064", ITcIoUdpProtocolRecv)
#endif // !defined(_TC_IID_03010095_0000_0000_E000_000000000064_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
