///////////////////////////////////////////////////////////////////////////////
// UdpDemoClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "UdpDemoClassFactory.h"
#include "UdpDemoServices.h"
#include "UdpDemoVersion.h"
#include "UdpDemo.h"

BEGIN_CLASS_MAP(CUdpDemoClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_UdpDemo, CID_UdpDemoCUdpDemo, SRVNAME_UDPDEMO "!CUdpDemo", CUdpDemo)
///</AutoGeneratedContent>
END_CLASS_MAP()

CUdpDemoClassFactory::CUdpDemoClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_UDPDEMO)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(UdpDemo));
#endif //defined(TCDBG_UNIT_VERSION)
}

