///////////////////////////////////////////////////////////////////////////////
// UdpDemoInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "UdpDemoServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_03010097_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_TYPE_03010097_0000_0000_E000_000000000064_INCLUDED_
struct __declspec(novtable) ITcIoUdpProtocol : public ITcUnknown
{
	virtual HRESULT TCOMAPI SendData(ULONG ipDestAddr, USHORT udpDestPort, USHORT udpSrcPort, ULONG nData, PVOID pData, bool bCalcUdpCheckSum=0, ETYPE_VLAN_HEADER* pVlan=0)=0;
	virtual HRESULT TCOMAPI CheckReceived()=0;
	virtual HRESULT TCOMAPI RegisterReceiver(USHORT udpPort, ITcIoUdpProtocolRecv* ipRecv)=0;
	virtual HRESULT TCOMAPI UnregisterReceiver(USHORT udpPort)=0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcIoUdpProtocol, IID_ITcIoUdpProtocol);
#endif // !defined(_TC_TYPE_03010097_0000_0000_E000_000000000064_INCLUDED_)

#if !defined(_TC_TYPE_03010095_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_TYPE_03010095_0000_0000_E000_000000000064_INCLUDED_
struct __declspec(novtable) ITcIoUdpProtocolRecv : public ITcUnknown
{
	virtual HRESULT TCOMAPI ReceiveData(ULONG ipAddr, USHORT udpDestPort, USHORT udpSrcPort, ULONG nData, PVOID pData, ETYPE_VLAN_HEADER* pVlan=0)=0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcIoUdpProtocolRecv, IID_ITcIoUdpProtocolRecv);
#endif // !defined(_TC_TYPE_03010095_0000_0000_E000_000000000064_INCLUDED_)

///</AutoGeneratedContent>
