///////////////////////////////////////////////////////////////////////////////
// PingClientClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "PingClientClassFactory.h"
#include "PingClientServices.h"
#include "PingClientVersion.h"
#include "PingModule.h"

BEGIN_CLASS_MAP(CPingClientClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_PingClient, CID_PingClientCPingModule, SRVNAME_PINGCLIENT "!CPingModule", CPingModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CPingClientClassFactory::CPingClientClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_PINGCLIENT)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(PingClient));
#endif //defined(TCDBG_UNIT_VERSION)
}

