///////////////////////////////////////////////////////////////////////////////
// PingClientInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "PingClientServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_03010096_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_TYPE_03010096_0000_0000_E000_000000000064_INCLUDED_
struct __declspec(novtable) ITcIoArpPingRecv : public ITcUnknown
{
	virtual HRESULT TCOMAPI ArpReply(ULONG ipAddr, ETHERNET_ADDRESS macAddr, ETYPE_VLAN_HEADER* pVlan=0)=0;
	virtual HRESULT TCOMAPI PingReply(ULONG ipAddr, ULONG nData, PVOID pData, ETYPE_VLAN_HEADER* pVlan=0)=0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcIoArpPingRecv, IID_ITcIoArpPingRecv);
#endif // !defined(_TC_TYPE_03010096_0000_0000_E000_000000000064_INCLUDED_)

#if !defined(_TC_TYPE_0301009E_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_TYPE_0301009E_0000_0000_E000_000000000064_INCLUDED_
struct __declspec(novtable) ITcIoArpPing : public ITcUnknown
{
	virtual HRESULT TCOMAPI PingRequest(ULONG ipAddr, ULONG nData=0, PVOID pData=0, ETYPE_VLAN_HEADER* pVlan=0)=0;
	virtual HRESULT TCOMAPI ArpRequest(ULONG ipAddr, ETHERNET_ADDRESS* macAddr=0, ETYPE_VLAN_HEADER* pVlan=0)=0;
	virtual HRESULT TCOMAPI RegisterReceiver(ITcIoArpPingRecv* ipRecv)=0;
	virtual HRESULT TCOMAPI UnregisterReceiver(ITcIoArpPingRecv* ipRecv)=0;
	virtual HRESULT TCOMAPI CheckReceived()=0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcIoArpPing, IID_ITcIoArpPing);
#endif // !defined(_TC_TYPE_0301009E_0000_0000_E000_000000000064_INCLUDED_)

///</AutoGeneratedContent>
